	#! /bin/bash

# This script will upload the lactobacilli genomes to PHASTER for detection of prophages
#### Use the codes below if you already have the sequences, otherwise use the next block of codes
## unzip files in folder  
for file in *.gz
do
	gunzip $file # this will remove the .gz file format , hence the files will be in .fna format
done
## upload to Phaster server
for genome in *.fna		# for each genomes files in folder that ends with .fna
do
	chmod u+rwx $genome		#grant permission to write, read and execute file
	wget --post-file="$genome" "http://phaster.ca/phaster_api?contigs=1" -O Output_"$genome"		# upload the file to PHASTER server and save result as Output_*(where * is the name of the genome file)
done


## upload with genome accession number
file="/mnt/c/Users/Nnamdi/Desktop/thesisMain/data/genomes.txt"   ## a file containing all accession numbers
while read -r line
do
	wget "http://phaster.ca/phaster_api?acc=$line" -O "$line.txt"
done < $file


download from Phaster server
for genome in Output_*.fna
do
	ID=$(grep "ZZ_*" $genome)	# define an ID which is generated by matching the regex in the job ID files generated by PHASTER after submission
	wget "http://phaster.ca/phaster_api?acc="$ID"" -O result+"$genome" # use the IDs to download the file from PHASTER and save results as "result+'name of genome'"
done


